#!/usr/bin/env python3
import sys
import os
from termcolor import colored
from helpers import get_user_timeline
from analyzer import Analyzer

def main():

    # get (and check) command line arguments
    if len(sys.argv) != 2:
        print("Usage: ./tweets @screen_name")
        exit(1)

    screen_name = sys.argv[1]

    # strip leading @ (if exists)
    if screen_name.startswith('@'):
        screen_name = screen_name[1:]

    # set up and instantiate analyzer
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    analyzer = Analyzer(positives, negatives)

    # fetch and analyze last 50 tweets of user
    tweets = get_user_timeline(screen_name, count=50)

    for tweet in tweets:
        # get score for each tweet
        score = analyzer.analyze(tweet)

        # output each tweet’s score and text, coloured as suitable
        if score > 0:
            print(colored("%2d: %s" % (score, tweet), "green"))
        elif score < 0:
            print(colored("%2d: %s" % (score, tweet), "red"))
        else:
            print(colored("%2d: %s" % (score, tweet), "yellow"))

if __name__ == '__main__':
    main()